sudo: false

language: node_js

node_js:
  - lts/*

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - npm run lint<% if (features.includes('test')) { %>
  - npm run test<% if (features.includes('coverage')) { %>

after_script:
  - npx codecov<% } %><% } %>
