const fs = require('fs')
const { join } = require('path')
const { default: caz, inject } = require('caz')

const temp = join(__dirname, 'temp')
const template = join(temp, 'src')

beforeAll(async () => {
  jest.spyOn(console, 'log').mockImplementation()
  jest.spyOn(console, 'clear').mockImplementation()
  await fs.promises.mkdir(template, { recursive: true })
  await fs.promises.cp(join(__dirname, 'index.js'), join(template, 'index.js'))
  await fs.promises.cp(join(__dirname, 'package.json'), join(template, 'package.json'))
  await fs.promises.cp(join(__dirname, 'template'), join(template, 'template'), { recursive: true })
})

test('minimal', async () => {
  inject(['minimal', '0.1.0', 'minimal template', 'zce', 'w@zce.me', 'https://zce.me', 'MIT', 'zce', [], false, 'npm'])
  const project = join(temp, 'minimal')
  await caz(template, project, { force: true })
  expect(fs.existsSync(project)).toBe(true)
  expect(fs.existsSync(join(project, '.git'))).toBe(true)
  expect(fs.existsSync(join(project, '.github/workflows/main.yml'))).toBe(true)
  expect(fs.existsSync(join(project, 'lib/index.js'))).toBe(true)
  expect(fs.existsSync(join(project, '.editorconfig'))).toBe(true)
  expect(fs.existsSync(join(project, '.gitignore'))).toBe(true)
  expect(fs.existsSync(join(project, 'CHANGELOG.md'))).toBe(true)
  expect(fs.existsSync(join(project, 'LICENSE'))).toBe(true)
  expect(fs.existsSync(join(project, 'package.json'))).toBe(true)
  expect(fs.existsSync(join(project, 'README.md'))).toBe(true)
})

test('maximal', async () => {
  inject(['maximal', '0.1.0', 'maximal template', 'zce', 'w@zce.me', 'https://zce.me', 'MIT', 'zce', ['test', 'typescript', 'cli', 'docs', 'example'], false, 'npm'])
  const project = join(temp, 'maximal')
  await caz(template, project, { force: true })
  expect(fs.existsSync(project)).toBe(true)
  expect(fs.existsSync(join(project, '.git'))).toBe(true)
  expect(fs.existsSync(join(project, '.github/workflows/main.yml'))).toBe(true)
  expect(fs.existsSync(join(project, 'bin/maximal.js'))).toBe(true)
  expect(fs.existsSync(join(project, 'docs/maximal.md'))).toBe(true)
  expect(fs.existsSync(join(project, 'example/usage.ts'))).toBe(true)
  expect(fs.existsSync(join(project, 'src/cli.ts'))).toBe(true)
  expect(fs.existsSync(join(project, 'src/index.ts'))).toBe(true)
  expect(fs.existsSync(join(project, 'test/index.test.ts'))).toBe(true)
  expect(fs.existsSync(join(project, '.editorconfig'))).toBe(true)
  expect(fs.existsSync(join(project, '.gitignore'))).toBe(true)
  expect(fs.existsSync(join(project, 'CHANGELOG.md'))).toBe(true)
  expect(fs.existsSync(join(project, 'LICENSE'))).toBe(true)
  expect(fs.existsSync(join(project, 'package.json'))).toBe(true)
  expect(fs.existsSync(join(project, 'README.md'))).toBe(true)
  expect(fs.existsSync(join(project, 'tsconfig.eslint.json'))).toBe(true)
  expect(fs.existsSync(join(project, 'tsconfig.json'))).toBe(true)
})

afterAll(async () => {
  jest.clearAllMocks()
  await fs.promises.rm(temp, { recursive: true })
})
